# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  container-mysql-dt:
    driver: local

services:
  # MySQL (5.7)
  moodledb:
    image: mysql:5.7
    container_name: container-moodledb
    volumes:
      - container-mysql-dt:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=containerdb
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=efBlMFIHmQYH158h
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # PHP 7.0
  php:
    build: ./php/
    container_name: container-php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./moodle/:/var/www/html
    links:
      - moodledb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # NGINX
  web:
    image: nginx:latest
    container_name: container-nginx
    ports:
      - "8091:80"
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container-phpmyadmin
    ports:
        - 8080:80
    links:
        - moodledb
    environment:
        PMA_HOST: moodledb
